version: "3"
services:
  yolov7_arm64:
    image: yolov7_arm64:v0.0.2
    volumes:
      - .:/app
    ports:
      - "8012:8012"
    command: python3 api.py
    # command: top
    tty: true
    runtime: nvidia
